
SOURCE_REPOSITORY_URL=https://github.com/Abhinish13/CandyGameApi.git
SOURCE_REPOSITORY_REF=leaderboard
APPLICATION_DOMAIN=candygameapi.apps.d94a.example.opentlc.com 
DATABASE_USER=dbuser
DATABASE_PASSWORD=Prodev1qaz
DATABASE_NAME=player
DATABASE_ADMIN_PASSWORD=Password
SOURCE_REPOSITORY_REF=leaderboard
